"use client";

/**
 * InterventionsPanel — Teacher interventions dashboard UI (M8-01).
 *
 * Displays intervention recommendations generated by the intervention agent:
 *   - Urgency indicator (1–4, 4 = most urgent) with color-coded badge.
 *   - Trigger reason (persistent gap, regression, non-responder) with evidence summary.
 *   - Approve / Dismiss actions per recommendation.
 *   - Status filter: pending (default), approved, dismissed, all.
 *   - Status history display with actioned_at timestamp for resolved items.
 *
 * Data source:
 *   - GET /interventions?status=<filter>   — React Query
 *   - POST /interventions/{id}/approve     — useMutation
 *   - DELETE /interventions/{id}           — useMutation
 *
 * Security:
 *   - No student PII in query keys — entity IDs only.
 *   - Student IDs from recommendation items are used for links only (UUID).
 *   - No student data written to localStorage or sessionStorage.
 */

import { useState } from "react";
import Link from "next/link";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  listInterventions,
  approveIntervention,
  dismissIntervention,
} from "@/lib/api/interventions";
import type {
  InterventionRecommendation,
  InterventionTriggerType,
  InterventionStatusFilter,
} from "@/lib/api/interventions";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TRIGGER_LABELS: Record<InterventionTriggerType, string> = {
  regression: "Score Regression",
  non_responder: "No Improvement After Feedback",
  persistent_gap: "Persistent Skill Gap",
  high_inconsistency: "High Inconsistency",
  trajectory_risk: "Trajectory Risk",
};

const URGENCY_LABELS: Record<number, string> = {
  1: "Low",
  2: "Medium",
  3: "High",
  4: "Critical",
};

const URGENCY_CLASSES: Record<number, string> = {
  1: "bg-gray-100 text-gray-700",
  2: "bg-blue-100 text-blue-700",
  3: "bg-yellow-100 text-yellow-800",
  4: "bg-red-100 text-red-700",
};

const URGENCY_INDICATOR_CLASSES: Record<number, string> = {
  1: "bg-gray-400",
  2: "bg-blue-500",
  3: "bg-yellow-500",
  4: "bg-red-500",
};

const STATUS_LABELS: Record<string, string> = {
  pending_review: "Pending Review",
  approved: "Approved",
  dismissed: "Dismissed",
};

const STATUS_BADGE_CLASSES: Record<string, string> = {
  pending_review: "bg-yellow-100 text-yellow-800",
  approved: "bg-green-100 text-green-800",
  dismissed: "bg-gray-100 text-gray-600",
};

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

interface InterventionCardProps {
  item: InterventionRecommendation;
  onApprove: (id: string) => void;
  onDismiss: (id: string) => void;
  isPending: boolean;
}

function InterventionCard({
  item,
  onApprove,
  onDismiss,
  isPending,
}: InterventionCardProps) {
  const urgencyLabel = URGENCY_LABELS[item.urgency] ?? String(item.urgency);
  const urgencyClass = URGENCY_CLASSES[item.urgency] ?? "bg-gray-100 text-gray-700";
  const indicatorClass = URGENCY_INDICATOR_CLASSES[item.urgency] ?? "bg-gray-400";
  const triggerLabel = TRIGGER_LABELS[item.trigger_type] ?? item.trigger_type;
  const statusLabel = STATUS_LABELS[item.status] ?? item.status;
  const statusBadgeClass =
    STATUS_BADGE_CLASSES[item.status] ?? "bg-gray-100 text-gray-600";
  const isPendingReview = item.status === "pending_review";

  const formattedCreatedAt = new Date(item.created_at).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const formattedActionedAt = item.actioned_at
    ? new Date(item.actioned_at).toLocaleDateString(undefined, {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : null;

  return (
    <li
      className="rounded-lg border border-gray-200 bg-white shadow-sm"
      aria-label={`Intervention: ${triggerLabel}, urgency ${urgencyLabel}, status ${statusLabel}`}
    >
      <div className="flex items-start gap-3 px-4 py-4">
        {/* Urgency indicator dot */}
        <div className="mt-1 flex-shrink-0">
          <span
            className={`block h-3 w-3 rounded-full ${indicatorClass}`}
            aria-hidden="true"
          />
        </div>

        {/* Main content */}
        <div className="min-w-0 flex-1">
          {/* Top row: trigger label + urgency badge + status badge */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-semibold text-gray-900">{triggerLabel}</span>
            <span
              className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${urgencyClass}`}
            >
              {urgencyLabel}
            </span>
            {item.skill_key && (
              <span className="rounded-full bg-purple-100 px-2.5 py-0.5 text-xs font-medium text-purple-700">
                {item.skill_key}
              </span>
            )}
            <span
              className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${statusBadgeClass}`}
            >
              {statusLabel}
            </span>
          </div>

          {/* Trigger reason */}
          <p className="mt-1.5 text-sm text-gray-700">{item.trigger_reason}</p>

          {/* Evidence summary */}
          <p className="mt-1 text-xs text-gray-500">{item.evidence_summary}</p>

          {/* Suggested action */}
          <p className="mt-1.5 text-sm font-medium text-gray-800">
            Suggested: {item.suggested_action}
          </p>

          {/* Student profile link — accessible name uses no PII, only UUID in href */}
          <Link
            href={`/dashboard/students/${item.student_id}`}
            aria-label={`View student profile (ID: ${item.student_id})`}
            className="mt-1 inline-block text-xs font-medium text-blue-600 underline hover:text-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            View student profile →
          </Link>

          {/* Status history */}
          <div className="mt-2 flex flex-wrap gap-3 text-xs text-gray-400">
            <span>Created: {formattedCreatedAt}</span>
            {formattedActionedAt && (
              <span>
                {item.status === "approved" ? "Approved" : "Dismissed"}:{" "}
                {formattedActionedAt}
              </span>
            )}
          </div>
        </div>

        {/* Action controls — only shown for pending_review items */}
        {isPendingReview && (
          <div className="flex flex-shrink-0 flex-col gap-1 sm:flex-row sm:gap-2">
            <button
              type="button"
              onClick={() => onApprove(item.id)}
              disabled={isPending}
              aria-label="Approve intervention"
              className="rounded px-2.5 py-1 text-xs font-medium text-green-700 ring-1 ring-green-300 hover:bg-green-50 focus:outline-none focus:ring-2 focus:ring-green-500 disabled:opacity-50"
            >
              Approve
            </button>
            <button
              type="button"
              onClick={() => onDismiss(item.id)}
              disabled={isPending}
              aria-label="Dismiss intervention"
              className="rounded px-2.5 py-1 text-xs font-medium text-gray-600 ring-1 ring-gray-300 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-400 disabled:opacity-50"
            >
              Dismiss
            </button>
          </div>
        )}
      </div>
    </li>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

interface InterventionsPanelProps {
  /**
   * Initial status filter — can be set from query params when navigating from
   * worklist items to preserve context.
   */
  initialStatus?: InterventionStatusFilter;
}

export function InterventionsPanel({
  initialStatus = "pending_review",
}: InterventionsPanelProps) {
  const queryClient = useQueryClient();

  // ----- Filter state -----
  const [statusFilter, setStatusFilter] =
    useState<InterventionStatusFilter>(initialStatus);

  // ----- Data fetch -----
  const {
    data: interventions,
    isLoading,
    isError,
  } = useQuery({
    queryKey: ["interventions", statusFilter],
    queryFn: () => listInterventions(statusFilter),
  });

  // ----- Mutations -----
  const approveMutation = useMutation({
    mutationFn: (id: string) => approveIntervention(id),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["interventions"] });
    },
  });

  const dismissMutation = useMutation({
    mutationFn: (id: string) => dismissIntervention(id),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["interventions"] });
    },
  });

  const isPending = approveMutation.isPending || dismissMutation.isPending;

  // ----- Loading -----
  if (isLoading) {
    return (
      <div aria-live="polite" aria-busy="true" className="space-y-3">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-24 animate-pulse rounded-lg bg-gray-200" />
        ))}
      </div>
    );
  }

  // ----- Error -----
  if (isError) {
    return (
      <p
        role="alert"
        className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-700"
      >
        Failed to load interventions. Please refresh the page.
      </p>
    );
  }

  const allItems = interventions?.items ?? [];

  return (
    <div className="space-y-4">
      {/* Status filter */}
      <div className="flex items-center gap-3" role="group" aria-label="Intervention filters">
        <label htmlFor="filter-status" className="sr-only">
          Filter by status
        </label>
        <select
          id="filter-status"
          value={statusFilter}
          onChange={(e) => {
            const v = e.target.value as InterventionStatusFilter;
            const valid: InterventionStatusFilter[] = [
              "pending_review",
              "approved",
              "dismissed",
              "all",
            ];
            if (valid.includes(v)) {
              setStatusFilter(v);
            }
          }}
          className="rounded border border-gray-300 bg-white px-2 py-1 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="pending_review">Pending Review</option>
          <option value="approved">Approved</option>
          <option value="dismissed">Dismissed</option>
          <option value="all">All Interventions</option>
        </select>

        <p className="text-sm text-gray-500">
          {allItems.length} {allItems.length === 1 ? "item" : "items"}
        </p>
      </div>

      {/* Empty state */}
      {allItems.length === 0 ? (
        <div className="rounded-lg border-2 border-dashed border-gray-200 p-8 text-center">
          <p className="text-sm font-medium text-gray-700">
            {statusFilter === "pending_review"
              ? "No pending interventions."
              : "No interventions found for this filter."}
          </p>
          {statusFilter === "pending_review" && (
            <p className="mt-1 text-xs text-gray-500">
              The intervention agent will surface recommendations when students show
              persistent skill gaps, score regressions, or non-response patterns.
            </p>
          )}
        </div>
      ) : (
        <ul className="space-y-2" role="list" aria-label="Intervention recommendations">
          {allItems.map((item) => (
            <InterventionCard
              key={item.id}
              item={item}
              onApprove={(id) => approveMutation.mutate(id)}
              onDismiss={(id) => dismissMutation.mutate(id)}
              isPending={isPending}
            />
          ))}
        </ul>
      )}

      {/* Mutation error feedback */}
      {approveMutation.isError && (
        <p role="alert" className="text-xs text-red-600">
          Failed to approve intervention. Please try again.
        </p>
      )}
      {dismissMutation.isError && (
        <p role="alert" className="text-xs text-red-600">
          Failed to dismiss intervention. Please try again.
        </p>
      )}
    </div>
  );
}
