"""StudentGroup ORM model.

Stores automatically-computed skill-gap groups for a class.  One row per
(teacher_id, class_id, skill_key) triplet — the unique constraint guarantees
that re-computing groups for the same class is idempotent.

Design decisions:
- ``teacher_id`` is stored directly on this table so the RLS policy can use
  an efficient equality check, matching the pattern used by other tenant-scoped
  tables (students, classes, student_skill_profiles, etc.).
- ``student_ids`` is a JSONB array of student UUID strings — the set of
  students in this group who share the underperforming ``skill_key``.
- ``student_count`` mirrors ``len(student_ids)`` and is stored to enable fast
  COUNT-style queries without expanding the JSONB array.
- ``computed_at`` records when this group was last recomputed so the M6-02 API
  can surface group freshness information.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.models.base import Base


class StudentGroup(Base):
    """A skill-gap student group for a class, generated by the auto-grouping task."""

    __tablename__ = "student_groups"

    __table_args__ = (
        UniqueConstraint(
            "teacher_id",
            "class_id",
            "skill_key",
            name="uq_student_groups_class_skill",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    teacher_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE", name="fk_student_groups_users"),
        nullable=False,
        index=True,
    )
    class_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("classes.id", ondelete="CASCADE", name="fk_student_groups_classes"),
        nullable=False,
        index=True,
    )
    # Canonical skill dimension key (e.g. "evidence", "thesis", "organization").
    skill_key: Mapped[str] = mapped_column(String(200), nullable=False)
    # Human-readable label derived from the skill key
    # (e.g. "Evidence" for "evidence").
    label: Mapped[str] = mapped_column(String(200), nullable=False)
    # JSONB array of student UUID strings sharing this underperforming skill.
    student_ids: Mapped[list[str]] = mapped_column(
        JSONB,
        nullable=False,
        server_default="'[]'::jsonb",
    )
    # Denormalised count — mirrors len(student_ids) for fast queries.
    student_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    # Timestamp of the most recent group computation for this class+skill pair.
    computed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
