"""TeacherWorklistItem ORM model.

Stores the ranked, teacher-facing worklist items generated from student
skill profile signals.  Each row represents one actionable signal for a
specific student, with a trigger type, urgency score, suggested action,
and lifecycle status.

Design decisions:
- ``teacher_id`` is stored directly on this table so that the RLS policy
  can use an efficient equality check (matching the pattern used by
  ``students``, ``classes``, ``student_skill_profiles``, etc.).
- ``trigger_type`` is a VARCHAR, not a DB ENUM, to avoid migration costs
  when new signal types are introduced.  The service layer constrains
  valid values.
- ``skill_key`` is nullable — student-level triggers (e.g. ``non_responder``)
  are not specific to a single skill dimension.
- ``urgency`` is an integer (1–4) where 4 = most urgent.  Items are
  displayed to the teacher ordered by urgency descending.
- ``details`` is a JSONB blob for signal-specific context (std_dev,
  avg_score, improvement, etc.) that does not need to be queried directly.
- ``status`` tracks lifecycle: 'active' → 'completed' | 'snoozed' | 'dismissed'.
  Active items are shown by default; others are hidden unless the caller
  explicitly requests all statuses.
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.models.base import Base


class TeacherWorklistItem(Base):
    """One actionable student signal in the teacher's worklist."""

    __tablename__ = "teacher_worklist_items"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    teacher_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE", name="fk_worklist_items_users"),
        nullable=False,
        index=True,
    )
    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("students.id", ondelete="CASCADE", name="fk_worklist_items_students"),
        nullable=False,
        index=True,
    )
    # Signal type: 'persistent_gap' | 'regression' | 'high_inconsistency' | 'non_responder'
    trigger_type: Mapped[str] = mapped_column(String(30), nullable=False)
    # Canonical skill dimension key (e.g. 'evidence').  NULL for student-level signals.
    skill_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    # Urgency level 1–4; 4 = most urgent.
    urgency: Mapped[int] = mapped_column(Integer, nullable=False)
    # Concrete action suggestion for the teacher.
    suggested_action: Mapped[str] = mapped_column(Text, nullable=False)
    # Signal-specific context: std_dev, avg_score, improvement, etc.
    details: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        server_default="'{}'::jsonb",
    )
    # Lifecycle: 'active' | 'snoozed' | 'completed' | 'dismissed'
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="'active'",
    )
    snoozed_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    # When this item was generated by the worklist computation task.
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
